# Regenerates exports.def by extracting all exports from miles32.dll.
# Each export becomes a forwarder of the form:  name = miles32.name
#
# Re-run this if miles32.dll changes. Safe to re-run anytime.

$ErrorActionPreference = "Stop"

$here   = Split-Path -Parent $MyInvocation.MyCommand.Path
$obj    = "$here\..\tools\mingw\bin\objdump.exe"
$miles  = "$here\..\game-test\miles32.dll"
$outDef = "$here\exports.def"

if (-not (Test-Path $obj))   { throw "objdump not found at $obj" }
if (-not (Test-Path $miles)) { throw "miles32.dll not found at $miles" }

# objdump -p prints sections incl. [Ordinal/Name Pointer] Table with names
$raw = & $obj -p $miles | Out-String
$start = $raw.IndexOf("[Ordinal/Name Pointer]")
if ($start -lt 0) { throw "Couldn't locate [Ordinal/Name Pointer] section in objdump output" }

$names = ($raw.Substring($start) -split "`n") |
    ForEach-Object {
        if ($_ -match '^\s*\[\s*\d+\]\s+(\S+)\s*$') { $matches[1] }
    } |
    Where-Object { $_ -and $_ -notmatch '^DllMain' }

if ($names.Count -lt 100) {
    throw "Only $($names.Count) names extracted - sanity check failed"
}

# Compose .def
$lines = @()
$lines += "; Auto-generated by gen-exports.ps1 - do not edit by hand."
$lines += "; Source: miles32.dll  (extracted via objdump -p)"
$lines += "; $($names.Count) forwarders to miles32.dll"
$lines += ""
$lines += "LIBRARY mss32"
$lines += "EXPORTS"
foreach ($n in $names) {
    $lines += "    $n = miles32.$n"
}

# ASCII output - linker requires plain ASCII for .def
[System.IO.File]::WriteAllLines($outDef, $lines, [System.Text.Encoding]::ASCII)

Write-Host "Wrote $outDef ($($names.Count) forwarders)" -ForegroundColor Green
